---
- name: Wait for Suricata eve.json file to be created
  wait_for:
    path: /var/log/suricata/eve.json
    state: present
    timeout: 5
  ignore_errors: yes
  register: eve_json_check

- name: Add Elastic GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    filename: elastic-7.x

- name: Install Filebeat
  apt:
    name: filebeat
    state: present
    update_cache: yes

- name: Copy Filebeat configuration
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart filebeat

- name: Configure Filebeat modules
  template:
    src: suricata.yml.j2
    dest: /etc/filebeat/modules.d/suricata.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart filebeat

- name: Enable filebeat service
  systemd:
    name: filebeat
    enabled: yes
    state: started
