_meta:
  type: "roles"
  config_version: 2

custom_readall:
  reserved: false
  cluster_permissions:
    - "cluster:monitor/state"
    - "cluster:monitor/nodes/info"
    - "indices:data/read/mget"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "read"
        - "indices:admin/get"
        - "indices:admin/template/put"
        - "indices:data/read/mget"
    - index_patterns:
        - ".kibana*"
      allowed_actions:
        - "read"
        - "indices:admin/get"
        - "indices:admin/template/put"
        - "indices:data/read/mget"

custom_ingest:
  reserved: false
  cluster_permissions:
    - "cluster:monitor/nodes/stats"
    - "cluster:monitor/task/get"
    - "cluster:monitor/state"
    - "cluster:monitor/nodes/info"
    - "cluster:manage/opensearch/bulk"  # <-- Added for Data Prepper bulk ingest
    - "indices:data/write/bulk"         # <-- Add this line
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "create_index"
        - "manage"
        - "indices:admin/create"
        - "indices:admin/mapping/put"
        - "indices:admin/template/put"
        - "write"
        - "index"
        - "indices:data/write/bulk*"
        - "indices:admin/get"
        - "indices:data/read/mget"
    - index_patterns:
        - ".kibana*"
      allowed_actions:
        - "read"
        - "indices:admin/get"
        - "indices:admin/template/put"
        - "indices:data/read/mget"
