_meta:
  type: "rolesmapping"
  config_version: 2

custom_readall:
  reserved: false
  users:
    - "kibanaserver"
  backend_roles: []
  hosts: []

custom_ingest:
  reserved: false
  users:
    - "kibanaserver"
  backend_roles: []
  hosts: []
